version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env.development.local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development.local
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app
      # - ./path/to/your/google-cloud-key.json:/app/google-cloud-key.json

volumes:
  postgres_data: